# Generated by Django 4.2.25 on 2025-10-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL изображения')),
                ('cloudinary_public_id', models.CharField(max_length=255, verbose_name='Public ID в облаке')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея изображений',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
